# Generated by Django 4.0.6 on 2024-04-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacaoCurso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacientifica',
            old_name='nome',
            new_name='nome_area',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nome',
            new_name='nome_curso',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='nome',
            new_name='nome_disciplina',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='nome',
            new_name='nome_docente',
        ),
        migrations.RenameField(
            model_name='linguagemprogramacao',
            old_name='nome',
            new_name='nome_linguagem',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(max_length=20),
        ),
    ]
