# Generated by Django 4.0.6 on 2024-04-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacaoCurso', '0002_rename_nome_areacientifica_nome_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area_cientifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacaoCurso.areacientifica'),
        ),
    ]
