# Generated by Django 4.0.6 on 2024-04-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacaoCurso', '0003_alter_disciplina_area_cientifica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='docente',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacaoCurso.disciplina'),
        ),
    ]
