# Generated by Django 4.0.6 on 2024-04-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacaoCurso', '0004_remove_docente_disciplinas_docente_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='video_demo_link',
        ),
    ]
