# Generated by Django 4.0.6 on 2024-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacaoCurso', '0006_projeto_github_link_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacientifica',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='areas_cientificas', to='aplicacaoCurso.disciplina'),
        ),
    ]
