# Generated by Django 4.0.6 on 2024-04-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='festivais',
        ),
        migrations.AddField(
            model_name='banda',
            name='festival',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivais.festival'),
        ),
        migrations.AddField(
            model_name='festival',
            name='cartaz',
            field=models.ImageField(blank=True, null=True, upload_to='media/festivais/'),
        ),
    ]
