# Generated by Django 4.0.6 on 2024-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0002_remove_banda_festivais_banda_festival_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='festival',
        ),
        migrations.AddField(
            model_name='banda',
            name='festivais',
            field=models.ManyToManyField(to='festivais.festival'),
        ),
    ]
