# Generated by Django 4.0.6 on 2024-04-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_rename_nome_album_nome_do_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='genero',
        ),
    ]
