# Generated by Django 4.0.6 on 2024-05-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandas', '0005_remove_musica_album_delete_album_delete_banda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_album', models.CharField(max_length=100)),
                ('capa', models.ImageField(upload_to='capas_de_album')),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_banda', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100, null=True)),
                ('ano_criacao', models.IntegerField()),
                ('foto', models.ImageField(upload_to='foto_da_banda')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_musica', models.CharField(max_length=100)),
                ('duracao', models.PositiveIntegerField()),
                ('spotify_link', models.CharField(max_length=150)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandas.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandas.banda'),
        ),
    ]
