# Generated by Django 4.0.6 on 2024-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.CharField(max_length=100),
        ),
    ]
