# Generated by Django 4.0.6 on 2024-04-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacaoArtigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='nome',
            new_name='nome_avaliacao',
        ),
    ]
